apiVersion: apps/v1
kind: Deployment 
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-host
  name: nginx-host
spec:
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx-host
    spec:
      containers:
      - image: vaso0o0/nginx-host:%IMAGE-PLACEHOLDER%
        name: nginx-host
        ports:
        - containerPort: 80
        resources: {}   
      restartPolicy: Always
status: {}
